name: m3yen
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  lint:
  convex_bottom_bar: 
  cupertino_icons: 
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  permission_handler:
  firebase_core:
  provider:
  simple_animations: 
  url_launcher:
  country_code_picker: 
  flutter_vector_icons:
  image_picker:
  photo_view: 
  cached_network_image: 





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Bold.ttf
          weight: 700
    - family: TajawalRegular
      fonts:
        - asset: fonts/Tajawal-Regular.ttf
          weight: 700
    - family: AquinoDemo
      fonts:
        - asset: assets/fonts/AquinoDemo.ttf

    - family: Nisebuschgardens
      fonts:
        - asset: assets/fonts/Nisebuschgardens.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoBold.ttf